import {
  Application,
  Interview,
  Task,
  Company,
  Resume,
  TimelineEvent,
  KPIData,
} from './types';

export const kpiData: KPIData = {
  totalApplications: 47,
  activeApplications: 23,
  interviews: 8,
  offers: 2,
  responseRate: 34,
  applicationsThisWeek: 5,
};

export const applications: Application[] = [
  {
    id: 'app-1',
    jobTitle: 'Senior Frontend Engineer',
    company: 'Vercel',
    location: 'Remote, US',
    workMode: 'remote',
    employmentType: 'full-time',
    salary: '$180k - $220k',
    dateApplied: '2026-08-25',
    status: 'interview',
    priority: 'high',
    recruiter: 'Sarah Chen',
    notes: 'Great conversation with recruiter. Technical round scheduled for next week.',
    nextAction: 'Technical Interview',
    nextActionDate: '2026-08-30',
    jobUrl: 'https://vercel.com/careers/senior-frontend-engineer',
  },
  {
    id: 'app-2',
    jobTitle: 'Staff Software Engineer',
    company: 'Linear',
    location: 'San Francisco, CA',
    workMode: 'hybrid',
    employmentType: 'full-time',
    salary: '$200k - $260k',
    dateApplied: '2026-08-22',
    status: 'screening',
    priority: 'urgent',
    recruiter: 'Mike Johnson',
    notes: 'Referred by existing employee. Waiting for hiring manager review.',
    nextAction: 'Follow up with recruiter',
    nextActionDate: '2026-08-29',
  },
  {
    id: 'app-3',
    jobTitle: 'Product Engineer',
    company: 'Notion',
    location: 'New York, NY',
    workMode: 'hybrid',
    employmentType: 'full-time',
    salary: '$160k - $200k',
    dateApplied: '2026-08-20',
    status: 'applied',
    priority: 'high',
    notes: 'Submitted application through portal. Strong fit for the role.',
    nextAction: 'Wait for response',
    nextActionDate: '2026-09-03',
  },
  {
    id: 'app-4',
    jobTitle: 'Frontend Architect',
    company: 'Stripe',
    location: 'Remote, US',
    workMode: 'remote',
    employmentType: 'full-time',
    salary: '$220k - $280k',
    dateApplied: '2026-08-18',
    status: 'offer',
    priority: 'urgent',
    recruiter: 'Emily Davis',
    notes: 'Received verbal offer! Negotiating compensation package.',
    nextAction: 'Review offer letter',
    nextActionDate: '2026-08-28',
  },
  {
    id: 'app-5',
    jobTitle: 'Senior React Developer',
    company: 'Raycast',
    location: 'Remote, UK',
    workMode: 'remote',
    employmentType: 'full-time',
    salary: '£120k - £150k',
    dateApplied: '2026-08-15',
    status: 'interview',
    priority: 'medium',
    notes: 'Completed system design round. Awaiting feedback.',
    nextAction: 'Final round interview',
    nextActionDate: '2026-09-02',
  },
  {
    id: 'app-6',
    jobTitle: 'Full Stack Engineer',
    company: 'Figma',
    location: 'San Francisco, CA',
    workMode: 'hybrid',
    employmentType: 'full-time',
    salary: '$170k - $210k',
    dateApplied: '2026-08-12',
    status: 'rejected',
    priority: 'low',
    notes: 'Rejected after onsite. Feedback: looking for more backend depth.',
  },
  {
    id: 'app-7',
    jobTitle: 'Software Engineer II',
    company: 'Airbnb',
    location: 'San Francisco, CA',
    workMode: 'hybrid',
    employmentType: 'full-time',
    salary: '$150k - $190k',
    dateApplied: '2026-08-10',
    status: 'screening',
    priority: 'medium',
    recruiter: 'Tom Wilson',
    notes: 'Initial phone screen completed. Moving to technical round.',
    nextAction: 'Technical phone screen',
    nextActionDate: '2026-08-31',
  },
  {
    id: 'app-8',
    jobTitle: 'Senior UI Engineer',
    company: 'Plaid',
    location: 'Remote, US',
    workMode: 'remote',
    employmentType: 'full-time',
    salary: '$180k - $230k',
    dateApplied: '2026-08-08',
    status: 'applied',
    priority: 'medium',
    notes: 'Applied through company website.',
    nextAction: 'Wait for response',
  },
  {
    id: 'app-9',
    jobTitle: 'Principal Engineer',
    company: 'Datadog',
    location: 'New York, NY',
    workMode: 'hybrid',
    employmentType: 'full-time',
    salary: '$250k - $320k',
    dateApplied: '2026-08-05',
    status: 'wishlist',
    priority: 'low',
    notes: 'Found interesting role. Need to tailor resume before applying.',
    nextAction: 'Tailor resume',
  },
  {
    id: 'app-10',
    jobTitle: 'Frontend Engineer',
    company: 'Retool',
    location: 'San Francisco, CA',
    workMode: 'onsite',
    employmentType: 'full-time',
    salary: '$160k - $200k',
    dateApplied: '2026-08-03',
    status: 'interview',
    priority: 'high',
    recruiter: 'Lisa Park',
    notes: 'Great team fit. Onsite scheduled next week.',
    nextAction: 'Onsite interview',
    nextActionDate: '2026-09-01',
  },
  {
    id: 'app-11',
    jobTitle: 'Software Engineer',
    company: 'Supabase',
    location: 'Remote, Global',
    workMode: 'remote',
    employmentType: 'full-time',
    salary: '$140k - $180k',
    dateApplied: '2026-08-01',
    status: 'accepted',
    priority: 'high',
    notes: 'Accepted offer! Start date: October 1st.',
    nextAction: 'Sign offer letter',
    nextActionDate: '2026-08-27',
  },
  {
    id: 'app-12',
    jobTitle: 'Senior Developer',
    company: 'Shopify',
    location: 'Remote, Canada',
    workMode: 'remote',
    employmentType: 'full-time',
    salary: 'CAD $160k - $200k',
    dateApplied: '2026-07-28',
    status: 'withdrawn',
    priority: 'low',
    notes: 'Withdrew after accepting another offer.',
  },
  {
    id: 'app-13',
    jobTitle: 'Lead Frontend Engineer',
    company: 'Anthropic',
    location: 'San Francisco, CA',
    workMode: 'hybrid',
    employmentType: 'full-time',
    salary: '$240k - $300k',
    dateApplied: '2026-08-26',
    status: 'wishlist',
    priority: 'urgent',
    notes: 'Dream company. Need to prepare extensively before applying.',
    nextAction: 'Prepare portfolio',
  },
  {
    id: 'app-14',
    jobTitle: 'Engineering Manager',
    company: 'GitHub',
    location: 'Remote, US',
    workMode: 'remote',
    employmentType: 'full-time',
    salary: '$220k - $280k',
    dateApplied: '2026-08-24',
    status: 'applied',
    priority: 'medium',
    notes: 'Applied through referral.',
  },
  {
    id: 'app-15',
    jobTitle: 'Senior Product Designer',
    company: 'Loom',
    location: 'San Francisco, CA',
    workMode: 'hybrid',
    employmentType: 'full-time',
    salary: '$170k - $210k',
    dateApplied: '2026-08-21',
    status: 'screening',
    priority: 'medium',
    recruiter: 'Anna Lee',
    notes: 'Recruiter call went well. Preparing for portfolio review.',
    nextAction: 'Portfolio review',
    nextActionDate: '2026-09-04',
  },
];

export const interviews: Interview[] = [
  {
    id: 'int-1',
    applicationId: 'app-1',
    company: 'Vercel',
    jobTitle: 'Senior Frontend Engineer',
    type: 'technical',
    scheduledAt: '2026-08-30T10:00:00',
    duration: 60,
    interviewer: 'Sarah Chen',
    notes: 'Focus on React performance, edge functions, and system design.',
    status: 'scheduled',
  },
  {
    id: 'int-2',
    applicationId: 'app-5',
    company: 'Raycast',
    jobTitle: 'Senior React Developer',
    type: 'final',
    scheduledAt: '2026-09-02T14:00:00',
    duration: 90,
    interviewer: 'David Kim',
    notes: 'Final round with team lead and product manager.',
    status: 'scheduled',
  },
  {
    id: 'int-3',
    applicationId: 'app-10',
    company: 'Retool',
    jobTitle: 'Frontend Engineer',
    type: 'onsite',
    scheduledAt: '2026-09-01T09:00:00',
    duration: 180,
    interviewer: 'Lisa Park',
    notes: 'Full day onsite: 4 rounds including lunch with team.',
    status: 'scheduled',
  },
  {
    id: 'int-4',
    applicationId: 'app-7',
    company: 'Airbnb',
    jobTitle: 'Software Engineer II',
    type: 'phone',
    scheduledAt: '2026-08-31T11:00:00',
    duration: 45,
    interviewer: 'Tom Wilson',
    notes: 'Technical phone screen. Review data structures and algorithms.',
    status: 'scheduled',
  },
  {
    id: 'int-5',
    applicationId: 'app-15',
    company: 'Loom',
    jobTitle: 'Senior Product Designer',
    type: 'video',
    scheduledAt: '2026-09-04T13:00:00',
    duration: 60,
    interviewer: 'Anna Lee',
    notes: 'Portfolio review and design challenge discussion.',
    status: 'scheduled',
  },
  {
    id: 'int-6',
    applicationId: 'app-2',
    company: 'Linear',
    jobTitle: 'Staff Software Engineer',
    type: 'video',
    scheduledAt: '2026-08-28T15:00:00',
    duration: 60,
    interviewer: 'Mike Johnson',
    notes: 'Hiring manager conversation. Focus on architecture experience.',
    status: 'scheduled',
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Prepare for Vercel technical interview',
    description: 'Review React performance optimization and edge functions',
    dueDate: '2026-08-29',
    priority: 'urgent',
    completed: false,
    applicationId: 'app-1',
    category: 'preparation',
  },
  {
    id: 'task-2',
    title: 'Follow up with Linear recruiter',
    description: 'Check on application status after referral',
    dueDate: '2026-08-29',
    priority: 'high',
    completed: false,
    applicationId: 'app-2',
    category: 'follow-up',
  },
  {
    id: 'task-3',
    title: 'Review Stripe offer letter',
    description: 'Compare with market data and negotiate',
    dueDate: '2026-08-28',
    priority: 'urgent',
    completed: false,
    applicationId: 'app-4',
    category: 'document',
  },
  {
    id: 'task-4',
    title: 'Tailor resume for Anthropic',
    description: 'Highlight AI/ML experience and leadership',
    dueDate: '2026-09-05',
    priority: 'high',
    completed: false,
    applicationId: 'app-13',
    category: 'document',
  },
  {
    id: 'task-5',
    title: 'Send thank you note to Retool',
    description: 'Follow up after phone screen',
    dueDate: '2026-08-27',
    priority: 'medium',
    completed: true,
    applicationId: 'app-10',
    category: 'follow-up',
  },
  {
    id: 'task-6',
    title: 'Update portfolio website',
    description: 'Add recent projects and case studies',
    dueDate: '2026-09-10',
    priority: 'medium',
    completed: false,
    category: 'other',
  },
  {
    id: 'task-7',
    title: 'Connect with GitHub recruiter on LinkedIn',
    description: 'Build relationship before application review',
    dueDate: '2026-08-30',
    priority: 'low',
    completed: false,
    applicationId: 'app-14',
    category: 'networking',
  },
];

export const companies: Company[] = [
  {
    id: 'comp-1',
    name: 'Vercel',
    industry: 'Developer Tools',
    size: '500-1000',
    website: 'vercel.com',
    location: 'Remote, US',
    openPositions: 12,
    applicationsCount: 1,
  },
  {
    id: 'comp-2',
    name: 'Linear',
    industry: 'SaaS',
    size: '50-200',
    website: 'linear.app',
    location: 'San Francisco, CA',
    openPositions: 8,
    applicationsCount: 1,
  },
  {
    id: 'comp-3',
    name: 'Notion',
    industry: 'Productivity',
    size: '200-500',
    website: 'notion.so',
    location: 'New York, NY',
    openPositions: 15,
    applicationsCount: 1,
  },
  {
    id: 'comp-4',
    name: 'Stripe',
    industry: 'Fintech',
    size: '5000+',
    website: 'stripe.com',
    location: 'Remote, US',
    openPositions: 34,
    applicationsCount: 1,
  },
  {
    id: 'comp-5',
    name: 'Raycast',
    industry: 'Developer Tools',
    size: '50-200',
    website: 'raycast.com',
    location: 'Remote, UK',
    openPositions: 6,
    applicationsCount: 1,
  },
  {
    id: 'comp-6',
    name: 'Figma',
    industry: 'Design Tools',
    size: '1000-5000',
    website: 'figma.com',
    location: 'San Francisco, CA',
    openPositions: 22,
    applicationsCount: 1,
  },
  {
    id: 'comp-7',
    name: 'Airbnb',
    industry: 'Travel',
    size: '5000+',
    website: 'airbnb.com',
    location: 'San Francisco, CA',
    openPositions: 18,
    applicationsCount: 1,
  },
  {
    id: 'comp-8',
    name: 'Retool',
    industry: 'Developer Tools',
    size: '200-500',
    website: 'retool.com',
    location: 'San Francisco, CA',
    openPositions: 9,
    applicationsCount: 1,
  },
  {
    id: 'comp-9',
    name: 'Anthropic',
    industry: 'AI/ML',
    size: '200-500',
    website: 'anthropic.com',
    location: 'San Francisco, CA',
    openPositions: 14,
    applicationsCount: 1,
  },
  {
    id: 'comp-10',
    name: 'GitHub',
    industry: 'Developer Tools',
    size: '1000-5000',
    website: 'github.com',
    location: 'Remote, US',
    openPositions: 27,
    applicationsCount: 1,
  },
];

export const resumes: Resume[] = [
  {
    id: 'res-1',
    name: 'Frontend Engineer Resume',
    lastModified: '2026-08-20',
    fileSize: '248 KB',
    isDefault: true,
  },
  {
    id: 'res-2',
    name: 'Full Stack Resume',
    lastModified: '2026-08-15',
    fileSize: '312 KB',
    isDefault: false,
  },
  {
    id: 'res-3',
    name: 'Engineering Manager Resume',
    lastModified: '2026-07-30',
    fileSize: '289 KB',
    isDefault: false,
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: 'tl-1',
    applicationId: 'app-1',
    type: 'interview',
    title: 'Technical Interview Scheduled',
    description: 'Scheduled for August 30th at 10:00 AM',
    date: '2026-08-26',
  },
  {
    id: 'tl-2',
    applicationId: 'app-1',
    type: 'status_change',
    title: 'Status changed to Interview',
    description: 'Moved from Screening to Interview stage',
    date: '2026-08-25',
  },
  {
    id: 'tl-3',
    applicationId: 'app-1',
    type: 'email',
    title: 'Recruiter follow-up email',
    description: 'Sarah Chen reached out about next steps',
    date: '2026-08-24',
  },
  {
    id: 'tl-4',
    applicationId: 'app-1',
    type: 'status_change',
    title: 'Status changed to Screening',
    description: 'Application passed initial review',
    date: '2026-08-23',
  },
  {
    id: 'tl-5',
    applicationId: 'app-1',
    type: 'applied',
    title: 'Application Submitted',
    description: 'Applied through company website',
    date: '2026-08-25',
  },
];

export const applicationsOverTime = [
  { date: 'Jul W1', applications: 3, interviews: 0, offers: 0 },
  { date: 'Jul W2', applications: 5, interviews: 1, offers: 0 },
  { date: 'Jul W3', applications: 4, interviews: 2, offers: 0 },
  { date: 'Jul W4', applications: 6, interviews: 1, offers: 1 },
  { date: 'Aug W1', applications: 8, interviews: 3, offers: 0 },
  { date: 'Aug W2', applications: 7, interviews: 2, offers: 1 },
  { date: 'Aug W3', applications: 9, interviews: 4, offers: 0 },
  { date: 'Aug W4', applications: 5, interviews: 3, offers: 1 },
];

export const applicationFunnel = [
  { stage: 'Wishlist', count: 8, fill: 'hsl(var(--chart-1))' },
  { stage: 'Applied', count: 15, fill: 'hsl(var(--chart-2))' },
  { stage: 'Screening', count: 8, fill: 'hsl(var(--chart-3))' },
  { stage: 'Interview', count: 5, fill: 'hsl(var(--chart-4))' },
  { stage: 'Offer', count: 2, fill: 'hsl(var(--chart-5))' },
  { stage: 'Accepted', count: 1, fill: 'hsl(var(--success))' },
];

export const responseRateData = [
  { name: 'Responded', value: 34, fill: 'hsl(var(--success))' },
  { name: 'No Response', value: 66, fill: 'hsl(var(--muted-foreground) / 0.2)' },
];

export const statusDistribution = [
  { status: 'Wishlist', count: 8, fill: 'hsl(220 14% 50%)' },
  { status: 'Applied', count: 15, fill: 'hsl(217 91% 60%)' },
  { status: 'Screening', count: 8, fill: 'hsl(197 80% 55%)' },
  { status: 'Interview', count: 5, fill: 'hsl(243 75% 59%)' },
  { status: 'Offer', count: 2, fill: 'hsl(38 92% 50%)' },
  { status: 'Accepted', count: 1, fill: 'hsl(152 62% 45%)' },
  { status: 'Rejected', count: 6, fill: 'hsl(347 77% 60%)' },
  { status: 'Withdrawn', count: 2, fill: 'hsl(240 5% 50%)' },
];

export const weeklyActivity = [
  { day: 'Mon', applications: 2, interviews: 1 },
  { day: 'Tue', applications: 3, interviews: 0 },
  { day: 'Wed', applications: 1, interviews: 2 },
  { day: 'Thu', applications: 4, interviews: 1 },
  { day: 'Fri', applications: 2, interviews: 1 },
  { day: 'Sat', applications: 0, interviews: 0 },
  { day: 'Sun', applications: 1, interviews: 0 },
];

export const careerInsights = [
  {
    id: 'insight-1',
    title: 'Your response rate is above average',
    description:
      'At 34%, your response rate is 12% higher than the industry average. Your targeted applications are paying off.',
    type: 'positive',
    icon: 'trending-up',
  },
  {
    id: 'insight-2',
    title: 'Best time to apply is Tuesday',
    description:
      'Based on your data, applications submitted on Tuesdays have a 45% response rate compared to 28% on other days.',
    type: 'tip',
    icon: 'calendar',
  },
  {
    id: 'insight-3',
    title: 'Consider applying to more startups',
    description:
      'Startup applications have a 52% response rate vs 28% for enterprise companies in your history.',
    type: 'tip',
    icon: 'lightbulb',
  },
  {
    id: 'insight-4',
    title: 'Interview conversion is strong',
    description:
      '62% of your screening calls convert to technical interviews. Keep up the great preparation!',
    type: 'positive',
    icon: 'check-circle',
  },
];

export const faqs = [
  {
    question: 'Is CareerFlow free to use?',
    answer:
      'Yes! CareerFlow is free during our beta period. We will always offer a generous free tier for individual job seekers.',
  },
  {
    question: 'Can I track applications from any job board?',
    answer:
      'Absolutely. CareerFlow works with applications from any source — LinkedIn, Indeed, company websites, referrals, and more. Just add the application details and we handle the rest.',
  },
  {
    question: 'Does my data stay private?',
    answer:
      'Your data is yours. We never share your application data with employers or third parties. All information is encrypted and stored securely.',
  },
  {
    question: 'Can I export my data?',
    answer:
      'Yes, you can export all your application data as CSV or JSON at any time. No lock-in, ever.',
  },
  {
    question: 'Does CareerFlow have a mobile app?',
    answer:
      'CareerFlow is fully responsive and works beautifully on mobile browsers. Native iOS and Android apps are on our roadmap.',
  },
];
